version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    environment:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - ./www/backend:/var/www/backend  # Monta il backend
      - frontend-dist:/var/www/frontend/dist  # Volume dedicato per la cartella dist del frontend
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - '8089:80'
      - '8090:8080'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www/backend:/var/www/backend  # Monta il backend
      - frontend-dist:/var/www/frontend/dist  # Volume dedicato per la cartella dist del frontend
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:latest
    container_name: app-db
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - app
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

# Volumes
volumes:
  database:
    driver: local
  frontend-dist:
    driver: local
